name: Rebuild Algolia Self

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn

      - name: Generate fontlist
        run: yarn util:fontlist

      - name: Generate Algolia index
        run: yarn util:algolia
        env:
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_APPID: ${{ secrets.ALGOLIA_APPID }}

#       - name: Format files
#         run: yarn format

#       - name: Stage, commit and push files
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_user_name: "fontsource-bot"
#           commit_user_email: "83556432+fontsource-bot@users.noreply.github.com"
#           commit_author: "fontsource-bot <83556432+fontsource-bot@users.noreply.github.com>"
#           commit_message: "chore(build): update algolia"
#         continue-on-error: true
